### ISSUE TITLE
minidom error

### ISSUE THREAD

**Issue by pmuellr** [gutentags/tengwar.html#2]
Not sure if there's additional setup required to run `./build.sh`; tried running it after `git clone`ing the repo, then `npm install`ing, and got the following:

```
> ./build.sh
~/p/tengwar.html/node_modules/mr/node_modules/q/q.js:876
    throw error;
          ^
TypeError: Cannot set property length of [object Object] which has only a getter
    at Object.core.Node.insertBefore (file://~/p/tengwar.html/node_modules/gutentag/node_modules/domenic/node_modules/minidom/lib/dom-level1.js:556:30)
    at Object.core.Node.appendChild (file://~/p/tengwar.html/node_modules/gutentag/node_modules/domenic/node_modules/minidom/lib/dom-level1.js:674:17)
    at Object.core.Document.appendChild (file://~/p/tengwar.html/node_modules/gutentag/node_modules/domenic/node_modules/minidom/lib/dom-level1.js:1379:44)
    at Object.Handler.ontext (file://~/p/tengwar.html/node_modules/gutentag/node_modules/domenic/node_modules/minidom/minidom.js:59:22)
    at Parser.ontext (file://~/p/tengwar.html/node_modules/gutentag/node_modules/domenic/node_modules/minidom/node_modules/htmlparser2/lib/Parser.js:93:33)
    at Tokenizer._emitIfToken (file://~/p/tengwar.html/node_modules/gutentag/node_modules/domenic/node_modules/minidom/node_modules/htmlparser2/lib/Tokenizer.js:543:25)
    at Tokenizer.write (file://~/p/tengwar.html/node_modules/gutentag/node_modules/domenic/node_modules/minidom/node_modules/htmlparser2/lib/Tokenizer.js:93:10)
    at Tokenizer.end (file://~/p/tengwar.html/node_modules/gutentag/node_modules/domenic/node_modules/minidom/node_modules/htmlparser2/lib/Tokenizer.js:513:17)
    at Parser.end (file://~/p/tengwar.html/node_modules/gutentag/node_modules/domenic/node_modules/minidom/node_modules/htmlparser2/lib/Parser.js:239:18)
    at Parser.parseComplete (file://~/p/tengwar.html/node_modules/gutentag/node_modules/domenic/node_modules/minidom/node_modules/htmlparser2/lib/Parser.js:229:7)
```

**Comment by Stuk** [comment]
I'll try and take a look at this this morning

**Comment by kriskowal** [comment]
I observed this error as well, but not in Node 0.10. The problem manifests either in 0.12 or 1.0 (don’t recall which)

**Comment by Stuk** [comment]
@kriskowal I notice that domenic still depends on minidom 0.0.2, but 1.0.0 is available. That might fix this issue.

**Comment by kriskowal** [comment]
That appears to solve the problem locally. I’ll roll it up.

**Comment by Stuk** [comment]
Great!

**Comment by pmuellr** [comment]
I ran this on io.js v1.6.3

**Comment by kriskowal** [comment]
This issue is addressed on master. Pulling and reinstalling dependencies should resolve the issue. I am now working with node 0.12 and the build works.

**Comment by kriskowal** [comment]
And now I’m on iojs and all is well. Let me know if there are further problems!
